version: '2'

services:
  redis:
    image: redis:4
    container_name: sedaily-redis
  sedaily-api:
    image: softwaredaily/sedaily-rest-api
    container_name: sedaily-rest-api
    ports:
      - "4040:4040"
  mongo:
    image: softwaredaily/sedaily-mongo
    container_name: sedaily-mongo
