language: node_js
node_js:
  - "8.9.0"
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - docker-compose -f devops/docker-compose.yml up -d
  - npm run build:dev
  - npm start &
  - sleep 5
  - curl http://localhost:5000
  #- npm run test:e2e
