language: node_js
node_js:
  - "8.9.0"
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - npm run lint
  - docker-compose -f devops/docker-compose.yml up -d
  - npm run build:dev
  - npm run test:e2e
cache:
  directories:
    - ~/.npm
    - ~/.cache
